Develop
ro-msg-spring-training/online-shop-JurjiuDarius pull request #1
Opened 2022-09-28 10:05 UTC by JurjiuDarius

Completed the first part of the API chapter

2022-09-29 15:29 UTC, StefanMorar requested changes

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/ShopApplication.java
> +	CustomerRepository customerRepository;
Delete this line (unnecesary)

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/pom.xml
> +			<scope>runtime</scope>
Delete unused dependency: H2 is an alternative to PostgreSQL, we don't need it

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/ShopApplication.java
> +
Delete empty line

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/controller/OrderController.java
> +
Delete empty line

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/controller/OrderController.java
> +    }
Instead of this constructor you can use `@RequiredArgsConstructor`: https://projectlombok.org/api/lombok/RequiredArgsConstructor

Do the same for `OrderController`, `OrderService`, `ProductService`

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/ShopApplication.java
> +
Remove unused imports.  ![image](https://user-images.githubusercontent.com/45182894/193012870-376f47c3-f95d-4720-a3a3-54ed0d446919.png)

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/controller/ProductController.java
> +    }
You can remove this method

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/controller/ProductController.java
> +    public List<ProductReadDTO> allProducts() {
The names of the methods should follow the same structure. You have defined the following methods: `allProducts`, `findById` and `createProduct`: some of them have verbs (find, create), some of them don't; some of them include the word "product" (`allProducts`, `createProduct`), some don't (`findById`). Moreover, get == find, use only one of them.

I would suggest the following names: 
- Option 1: `getProducts`, `getProduct`, `createProduct`, etc
- Option 2: `getAll`, `getById`, `create`, `deleteById `etc
- Option 3: `get`, `get` (overloading: no parameters vs 1 parameter: ID), `create`, `delete `etc
- Option 4: something similar. You got the idea 😃 

Use the same convention in all your controllers

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/controller/ProductController.java
> +            return productService.findById(id);
1. The REST APIs should return a suggestive response body and status: here, in case of errors, you return an empty body with a 200 (OK) status.  We want to see that something went wrong: 404 (NOT FOUND), 400 (BAD REQUEST) status + and maybe an error message in the response body.

2. We could avoid adding catch blocks for every method by using a controller advice: https://www.baeldung.com/exception-handling-for-rest-with-spring#controlleradvice

Remind me to discuss about this for more details.

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/controller/ProductController.java
> +    public ProductReadDTO findById(@PathVariable("id") int id) {
No need to specify the path variable: https://www.baeldung.com/spring-pathvariable 

You can write: `public ProductReadDTO findById(@PathVariable int id) {`

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/repository/CustomerRepository.java
> +@Repository
Just so you know: the `@Repository` annotation is not necessary for interfaces that extend one of the predefined `Repository` interfaces (i.e., `CrudRepository`). You can remove it from every repository or leave it if you want.

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/repository/ProductRepository.java
> +import org.springframework.stereotype.Repository;
Remove unused import

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/service/LocationStrategy.java
> +    ArrayList<ProductLocationDTO> orderLocationStrategy(LocationRepository locationRepository, ArrayList<OrderDetail> orderDetails);
Also add an empty line before the method (if you added one after it). Try to respect the same approach in all classes/interfaces.

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/java/utils/CsvUtil.java
> +//        CsvMapper csvMapper=new CsvMapper();
Next time do not commit a file add that is not ready (do not include it when you run "git add")

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/resources/db/migration/V1_1__initialTables.sql
> +
Let's make this file prettier: https://www.sqlstyle.guide/#create-syntax: use tabs, write keywords in caps, read the other suggestions and adjust the queries.

Use the same spacing strategy: separate the queries by one empty line (not 2, not none)

The description of the migration file name (i.e., what follows the separator - double underscore) should follow the same pattern: for example, verb + object: `add_tables`, `populate_tables`, `add_primary_keys`, etc. Also, usually camel case is not used, so `initialTables` would become `initial_tables` or `add_initial_tables`

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/resources/db/migration/V1_1__initialTables.sql
> +location_id BIGINT,
`SERIAL` (used for primary keys in the other tables) is equivalent to `INT`, so use `INT` instead of `BIGINT`

The same for `order_detail`

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/resources/db/migration/V1_3__addingInstances.sql
> +
For the future: you can insert multiple rows with the same SQL statement (to avoid writing the again the column list): https://www.sqlservertutorial.net/sql-server-basics/sql-server-insert-multiple-rows/. You don't have to modify you code.

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/resources/db/migration/V1_1__initialTables.sql
> +weight double precision,
Check the mapping between [SQL and Java types](https://www.ibm.com/docs/en/informix-servers/12.10?topic=SSGU8G_12.1.0/com.ibm.esqlj.doc/ids_esqlj_023.htm). 

For example, `BIGINT` is not equivalent to `BigDecimal`.

Add the following property to `application.properties`: `spring.jpa.hibernate.ddl-auto=validate` to check the entities against tables.

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/resources/db/migration/V1_1__initialTables.sql
> +shipped_from_id BIGINT,
What's the difference between `shipped_from_id` and `location_id`?

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/entity/Stock.java
> +    private Location product;
Wrong type here (use `Product`)

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/entity/Customer.java
> +@RequiredArgsConstructor
`@Data` incorporates `@RequiredArgsConstructor`: https://projectlombok.org/features/Data

You can remove `@RequiredArgsConstructor` from all classes that also have `@Data`.

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/entity/Address.java
> +public class Address {
In other classes, you added an empty line after `{` and before `}`. Do the same here.

Modify the other classes too (I will not write a comment for all). Remove unnecessary empty lines too (for instance, the extra empty line in `Location`).

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/entity/Order.java
> +import java.util.ArrayList;
Delete unused import

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/entity/OrderDetailKey.java
> +    @Column(name = "order_id")
You can also specify `nullable = false`

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/entity/Product.java
> +    @OneToMany(mappedBy = "product")
When you have one-to-many relations, you don't have to include the relation in both entities unless it makes sense.

For instance: in `OrderDetail` you should have a product field because the order detail has no meaning without it. However, here in `Product` you don't have to add the `orderDetails` list (when you retrieve a product you don't have to read all the orders in which it is present - the list might be huge and doesn't add value to the object).

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/dto/order/OrderDTO.java
> +    private ArrayList<OrderDetailDTO> orderDetailDTOS;
This DTO contains the fields that must be included by the client that calls the REST API. It doesn't care that `orderDetailDTOS` is a DTO or not (this is an implementation detail). You should rename it to `orderDetails` to reflect its purpose only.

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/dto/order/OrderDTOMapper.java
> +
Move all mappers to a separate folder (it can be a subfolder inside `dto`). In Spring we separate the classes by their type: services, controllers, entities, so on, not by the entity they use. So, you don't have to add separate subfolders for orders and products. They are not so many and they are ordered alphabetically, so we have them grouped anyways.

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/dto/order/OrderDTOMapper.java
> +        }
Better move lines 19-28 to a private method.

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/dto/product/ProductLocationDTO.java
> +    public ProductLocationDTO(Product product, Location location, Integer quantity) {
You can use `@RequiredArgsConstructor` instead.

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/dto/product/ProductWriteDTO.java
> +    public ProductWriteDTO(String name, String description, BigDecimal price,
Unused constructor at the moment. In you need it, use `@RequiredArgsConstructor` instead, otherwise delete it.

2022-09-29 15:29 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/dto/product/ProductReadDTO.java
> +    public ProductReadDTO(String name, String description, BigDecimal price,
`@RequiredArgsConstructor` instead.

2022-09-30 05:25 UTC, JurjiuDarius commented on shop/shop/src/main/java/ro/msg/training/shop/repository/ProductRepository.java
> +import org.springframework.stereotype.Repository;
All imports are used in that file

2022-09-30 09:37 UTC, StefanMorar requested changes

2022-09-30 09:37 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/service/ProductService.java
> +
- Rename the methods (see the comment left for `ProductController`)
- Remove Sysouts and commented code
- Do not use DTOs in services (the service should return the base entity, the controller should make the conversion to the response DTO)
- If you are throwing runtime (unchecked) exceptions you don't have to add "throws  [...]" in the signature
-  Remove unused imports
- Place the private method at the end of the file (after all public methods)

Same remarks for `OrderService`

2022-09-30 09:37 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/service/ProductService.java
> +        return ProductDTOMapper.toDto(product.get());
"'Optional.get()' without 'isPresent()' check"

2022-09-30 09:37 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/service/ProductService.java
> +    private final ProductCategoryRepository productCategoryRepository;
A service should work with only one repository (i.e., the one that corresponds to the current entity). For example, ProductService should work with ProductRepository, OrderService should work with OrderRepository. 

If you need to access data from other tables, you should use services. For example, what you should do here is:

```
private final ProductRepository productRepository;
private final SupplierService supplierService;
private final ProductCategoryService productCategoryService;
```

Why do we use this approach? Let's have a look on your code. In `setSupplierAndCategory` you added the following lines:

```
Optional<Supplier> optionalSupplier = supplierRepository.findById(product.getSupplier().getId());
if (optionalSupplier.isEmpty()) {
          throw new RuntimeException("Supplier does not exist");
 }
```
If you directly call the repository of `Supplier`, every time you need to read something from it you have to add the `if` statement to check if `findById` is successful, so you repeat code. Instead, you should add a method in `SupplierService` that does both: calls findById and makes the additional check.

In this way we make an abstraction.

Try to always use this approach. Make the adjustments to `OrderService` too

2022-09-30 09:37 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/service/StrategyConfiguration.java
> +
It would be better to use an enum for all the possible strategies. 

FYI - Simple alternative for reading environment variables: `@Value("${locationStrategy}");`

2022-09-30 09:37 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/service/StrategyConfiguration.java
> +    }
Here you should create a bean (`@Bean`). https://docs.spring.io/spring-javaconfig/docs/1.0.0.M4/reference/html/ch02s02.html

2022-09-30 09:37 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/service/MostAbundantStrategy.java
> +    @Override
Move the strategy files to a subfolder inside "service"

2022-09-30 09:37 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/service/MostAbundantStrategy.java
> +    public ArrayList<ProductLocationDTO> orderLocationStrategy(LocationRepository locationRepository, ArrayList<OrderDetail> orderDetails) {
DTOs shouldn't be used at this layer. You can use `Stock` instead (it has same fields anyways)

2022-09-30 09:37 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/service/OrderService.java
> +    public Order createOrder(Order order) throws RuntimeException {
Consider using `@Transactional`: https://www.baeldung.com/transaction-configuration-with-jpa-and-spring

2022-09-30 09:37 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/service/OrderService.java
> +        }
You don't create the actual order in the DB (you have to persist it in the DB)

2022-10-03 06:48 UTC, StefanMorar requested changes

2022-10-03 06:48 UTC, StefanMorar commented on shop/shop/src/test/java/ro/msg/training/shop/ShopApplicationTests.java
> +
Delete the following files: `stock_export.txt`, `users.csv`, `stock_exports.csv`, `ModifiedUsers.csv`

2022-10-03 06:48 UTC, StefanMorar commented on shop/shop/.gitignore
> +src/main/java/ro/msg/training/shop/controller/StockController.java
Remove these 2 lines from .gitignore. When you have files you work on that you don't want to commit, simply don't add them with `git add` / make them unstaged or use `git stash`.

.gitingore is used for autogenerated files/IDE folders/installed libraries.

2022-10-03 06:48 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/controller/RestResponseEntityExceptionHandler.java
> +		return handleExceptionInternal(ex, bodyOfResponse, new HttpHeaders(), HttpStatus.CONFLICT, request);
Here a better status would be `HttpStatus.NOT_FOUND`

2022-10-03 06:48 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/dto/product/ProductLocationDTO.java
> +	public ProductLocationDTO(Product product, Location location, Integer quantity) {
There's an annotation you can use instead of this constructor

2022-10-03 06:48 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/dto/product/ProductReadDTO.java
> +public class ProductReadDTO implements Serializable {
Do this class and `ProductWriteDTO` still need to Serializable?

2022-10-03 06:48 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/entity/Product.java
> +	@JsonUnwrapped
Do you still need `@JsonUnwrapped`?

2022-10-03 06:48 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/service/OrderService.java
> +		ArrayList<Stock> productLocationDTOS = locationStrategy.orderLocationStrategy(locationService, new ArrayList<>(order.getOrderDetails()));
Rename variable (`productLocationDTOS`)

2022-10-03 06:48 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/service/strategies/LocationStrategy.java
> +package ro.msg.training.shop.service.strategies;
Package name: `strategy` (singular). Use singular or plural everywhere

2022-10-03 06:48 UTC, StefanMorar commented on shop/shop/src/main/java/ro/msg/training/shop/service/StrategyConfiguration.java
> +
Move file to `strategy` subfolder.

2022-10-03 07:51 UTC, merged